<?php

// CMS Seed Data — 22 keys untuk migrasi dari Express backend
return [
    'homepage' => [
        'eyebrow' => 'TRANSFORMASI DIGITAL',
        'headline' => 'Solusi ICT Terintegrasi untuk',
        'headlineAccent' => 'Bisnis Indonesia Modern',
        'headlineSuffix' => '& Berkelanjutan',
        'description' => 'Platform komprehensif menggabungkan infrastruktur IT, pembelajaran digital, dan inovasi AI untuk mengakselerasi transformasi organisasi Anda.',
        'primaryCtaText' => 'Konsultasi Gratis',
        'primaryCtaLink' => '#contact',
        'secondaryCtaText' => 'Lihat Portfolio',
        'secondaryCtaLink' => '#portfolio',
        'heroImage' => 'https://images.unsplash.com/photo-1451187580459-fdce2b798603?w=1100&h=440&fit=crop',
        'heroBadges' => [
            ['label' => 'ISO 9001:2015', 'icon' => 'award-line'],
            ['label' => 'TKDN Certified', 'icon' => 'shield-check-line'],
            ['label' => '15+ Tahun', 'icon' => 'calendar-line'],
            ['label' => 'Enterprise Scale', 'icon' => 'building-line'],
            ['label' => 'AI-Ready', 'icon' => 'robot-line'],
            ['label' => '24/7 Support', 'icon' => 'phone-line'],
        ],
    ],
    'trustBar' => [
        ['label' => 'Klien Puas', 'value' => '150+'],
        ['label' => 'Proyek Selesai', 'value' => '280+'],
        ['label' => 'Tim Expert', 'value' => '45+'],
        ['label' => 'Uptime', 'value' => '99.9%'],
        ['label' => 'Tahun Pengalaman', 'value' => '15+'],
    ],
    'about' => [
        'label' => 'TENTANG KAMI',
        'headline' => 'Mitra Transformasi Digital Terpercaya Indonesia',
        'paragraphs' => [
            'PT Dua Kawan Sejahtera Indonesia didirikan tahun 2010 sebagai mitra strategis untuk organisasi yang ingin mempercepat transformasi digital. Dengan keahlian mendalam dalam infrastruktur IT, pembelajaran digital, dan inovasi AI, kami telah membantu 150+ klien mencapai efisiensi operasional yang signifikan.',
            'Komitmen kami adalah memberikan solusi yang tidak hanya inovatif tetapi juga sustainable dan aligned dengan kebutuhan spesifik industri Indonesia. Tim kami yang berpengalaman siap mendampingi perjalanan digital Anda dari planning hingga maintenance.',
        ],
        'sectorEducation' => 'Transformasi pembelajaran dengan teknologi smart classroom dan digital literacy programs.',
        'sectorGovernment' => 'Infrastruktur digital yang aman dan scalable untuk layanan publik berkualitas.',
        'sectorEnterprise' => 'Solusi enterprise-grade untuk optimasi operasional dan business intelligence.',
        'ctaPrimary' => 'Lihat Sektor',
        'ctaSecondary' => 'Hub Kami',
    ],
    'sectors' => [
        'education' => [
            'desc' => 'Pembelajaran & Inovasi Digital',
            'sols' => ['Smart Classroom Integration', 'Microteaching Platform', 'Lab Bahasa Digital', 'Content Management'],
        ],
        'government' => [
            'desc' => 'Infrastruktur Publik Terpercaya',
            'sols' => ['Network Security', 'Datacenter Management', 'Government Cloud', 'Compliance & Governance'],
        ],
        'enterprise' => [
            'desc' => 'Solusi Bisnis Terintegrasi',
            'sols' => ['AI & Analytics', 'IoT Integration', 'Smart Office', 'Command Center'],
        ],
    ],
    'branding' => [
        'mainLogo' => '/logo/main.png',
        'secondaryLight' => '/logo/secondary-light.png',
        'secondaryDark' => '/logo/secondary-dark.png',
        'favicon' => '/logo/favicon.ico',
    ],
    'company' => [
        'name' => 'PT Dua Kawan Sejahtera Indonesia',
        'shortName' => 'DKSI',
        'tagline' => 'Solusi ICT Terintegrasi untuk Bisnis Indonesia',
        'subTagline' => 'Transformasi Digital dengan Expertise & Commitment',
        'established' => 2010,
        'address' => 'Jl. Gatot Subroto Kav. 8, Jakarta Selatan',
        'city' => 'Jakarta',
        'email' => 'info@dksi.co.id',
        'phone' => '+62-21-7274-0123',
        'website' => 'https://dksi.co.id',
        'stats' => [
            'cert1' => 'ISO 9001:2015 Certified',
            'cert2' => 'TKDN & Asuransi Cyber',
            'establishedLabel' => 'Founded 2010',
        ],
    ],
    'process' => [
        'label' => 'METODOLOGI',
        'headline' => 'Transformasi Terstruktur dalam 6 Fase',
        'steps' => [
            ['num' => '01', 'title' => 'Assessment', 'desc' => 'Audit menyeluruh infrastruktur & kebutuhan bisnis', 'detail' => 'Kami melakukan deep-dive analysis terhadap sistem existing, identifikasi gap, dan define roadmap transformasi yang realistic.'],
            ['num' => '02', 'title' => 'Planning', 'desc' => 'Strategi & timeline implementasi', 'detail' => 'Bersama stakeholder, kami merancang blueprint solusi dengan consideration terhadap budget, resource, dan business continuity.'],
            ['num' => '03', 'title' => 'Design', 'desc' => 'Arsitektur solusi enterprise-grade', 'detail' => 'Tim architect kami mendesain infrastructure yang secure, scalable, dan maintainable sesuai best practices industri.'],
            ['num' => '04', 'title' => 'Implementation', 'desc' => 'Deployment & integrasi sistem', 'detail' => 'Eksekusi implementation dengan minimal disruption, phased rollout, dan continuous testing untuk memastikan kualitas.'],
            ['num' => '05', 'title' => 'Training', 'desc' => 'Knowledge transfer & upskilling tim', 'detail' => 'Program training komprehensif untuk memastikan tim internal Anda siap operate dan maintain sistem baru.'],
            ['num' => '06', 'title' => 'Support', 'desc' => '24/7 monitoring & maintenance', 'detail' => 'Post-launch support dengan SLA guarantee, monitoring 24/7, dan continuous optimization untuk ROI maksimal.'],
        ],
    ],
    'services' => [
        [
            'tag' => '01',
            'icon' => 'server-line',
            'title' => 'IT Infrastructure',
            'sub' => 'Network & Datacenter',
            'desc' => 'Infrastruktur IT yang robust dan scalable dengan disaster recovery built-in.',
            'points' => ['Network Design', 'Datacenter Setup', 'Disaster Recovery'],
            'target' => 'Enterprise',
            'benefit' => 'Uptime 99.9%',
            'visible' => true,
        ],
        [
            'tag' => '02',
            'icon' => 'graduation-cap-line',
            'title' => 'Smart Education',
            'sub' => 'Digital Learning',
            'desc' => 'Platform pembelajaran digital dengan smart classroom dan microteaching integration.',
            'points' => ['Classroom Tech', 'LMS Platform', 'Analytics'],
            'target' => 'Education',
            'benefit' => 'Engage & Learn',
            'visible' => true,
        ],
        [
            'tag' => '03',
            'icon' => 'shield-check-line',
            'title' => 'Cybersecurity',
            'sub' => 'Protection & Compliance',
            'desc' => 'Solusi keamanan cyber terintegrasi dengan compliance management dan incident response.',
            'points' => ['Firewall & IDS', 'Vulnerability Assessment', 'Compliance'],
            'target' => 'Government',
            'benefit' => 'Protected 24/7',
            'visible' => true,
        ],
        [
            'tag' => '04',
            'icon' => 'robot-line',
            'title' => 'AI & IoT',
            'sub' => 'Smart Innovation',
            'desc' => 'Implementasi AI, IoT, dan big data analytics untuk business intelligence.',
            'points' => ['AI/ML Models', 'IoT Devices', 'Big Data'],
            'target' => 'Enterprise',
            'benefit' => 'Smart Insights',
            'visible' => true,
        ],
        [
            'tag' => '05',
            'icon' => 'phone-line',
            'title' => 'Managed Services',
            'sub' => 'Support & Operations',
            'desc' => '24/7 managed services dengan proactive monitoring dan performance optimization.',
            'points' => ['Monitoring', 'Support', 'Optimization'],
            'target' => 'All',
            'benefit' => 'Peace of Mind',
            'visible' => true,
        ],
    ],
    'solInfra' => [
        [
            'id' => 'infra-secure-network',
            'icon' => 'shield-network-line',
            'title' => 'Secure Network Infrastructure',
            'shortDesc' => 'Jaringan enterprise dengan high availability',
            'desc' => 'Infrastruktur jaringan berlapis dengan firewall, IDS/IPS, VPN, dan load balancing untuk keamanan maksimal.',
            'img' => 'https://images.unsplash.com/photo-1558494949-ef010cb60b97?w=600&h=400&fit=crop',
            'features' => ['SD-WAN', 'Redundancy', 'DDoS Protection', 'Zero Trust'],
            'benefits' => ['99.9% Uptime', 'Enterprise Grade', 'Compliant'],
            'status' => 'active',
        ],
        [
            'id' => 'infra-datacenter',
            'icon' => 'server-line',
            'title' => 'Managed Datacenter',
            'shortDesc' => 'Datacenter dengan disaster recovery',
            'desc' => 'Fasilitas datacenter modern dengan redundant power, cooling, dan geo-redundant backup untuk business continuity.',
            'img' => 'https://images.unsplash.com/photo-1451187580459-fdce2b798603?w=600&h=400&fit=crop',
            'features' => ['Geo-Redundant', 'Auto-Failover', 'Monitoring', 'Compliance'],
            'benefits' => ['24/7 Availability', 'Disaster Ready', 'Secure'],
            'status' => 'active',
        ],
    ],
    'solEdu' => [
        [
            'id' => 'edu-smartclass',
            'icon' => 'graduation-cap-line',
            'title' => 'Smart Classroom',
            'shortDesc' => 'Ruang kelas digital terintegrasi',
            'desc' => 'Integrasi teknologi interaktif di kelas untuk enhanced learning experience dengan real-time monitoring dan analytics.',
            'img' => 'https://images.unsplash.com/photo-1524178232363-1468b7ef7000?w=600&h=400&fit=crop',
            'features' => ['Interactive Display', 'Student Portal', 'Analytics', 'Mobile App'],
            'benefits' => ['Engagement+', 'Data-Driven', 'Scalable'],
            'status' => 'active',
        ],
    ],
    'solAi' => [
        [
            'id' => 'ai-smartcampus',
            'icon' => 'robot-line',
            'title' => 'Smart Campus',
            'shortDesc' => 'Campus management dengan AI',
            'desc' => 'Otomasi penuh manajemen kampus dengan smart access, resource allocation, dan predictive analytics untuk operational excellence.',
            'img' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
            'features' => ['Smart Access', 'AI Scheduler', 'Predictive Analytics', 'Mobile Portal'],
            'benefits' => ['Efficiency↑', 'Data Insights', 'User Experience'],
            'status' => 'active',
        ],
    ],
    'solCategories' => [
        ['id' => 'solInfra', 'name' => 'IT Infrastructure', 'desc' => 'Jaringan & datacenter secure', 'icon' => 'server-line', 'color' => 'royal'],
        ['id' => 'solEdu', 'name' => 'Smart Education', 'desc' => 'Platform pembelajaran digital', 'icon' => 'graduation-cap-line', 'color' => 'cyan'],
        ['id' => 'solAi', 'name' => 'AI & IoT', 'desc' => 'Inovasi dengan AI & IoT', 'icon' => 'robot-line', 'color' => 'navy'],
    ],
    'buildSmarter' => [
        'label' => 'KEUNGGULAN KAMI',
        'headline' => 'Build Smarter dengan',
        'headlineAccent' => 'DKSI Technology Stack',
        'description' => 'Kami menggunakan teknologi terdepan untuk memastikan solusi Anda high-performance, AI-ready, dan secure.',
        'cards' => [
            ['icon' => 'lightning-bolt-line', 'title' => 'High-Performance', 'desc' => 'Infrastruktur cloud-native dengan auto-scaling untuk performa optimal di setiap kondisi.'],
            ['icon' => 'robot-line', 'title' => 'AI-Ready', 'desc' => 'Didesain untuk integrasi machine learning dan predictive analytics yang seamless.'],
            ['icon' => 'shield-line', 'title' => 'Enterprise Secure', 'desc' => 'Keamanan berlapis dengan encryption, compliance audit, dan incident response 24/7.'],
        ],
    ],
    'why' => [
        ['icon' => 'award-line', 'title' => 'Expertise', 'desc' => '15+ tahun pengalaman dalam transformasi digital enterprise Indonesia.'],
        ['icon' => 'team-line', 'title' => 'Dedicated Team', 'desc' => '45+ profesional bersertifikat siap mendampingi project Anda end-to-end.'],
        ['icon' => 'customer-service-2-line', 'title' => 'Customer Success', 'desc' => '150+ klien puas dengan retention rate 95% karena kualitas service.'],
        ['icon' => 'shield-check-line', 'title' => 'Certified', 'desc' => 'ISO 9001:2015 & TKDN certified dengan audit trail compliance penuh.'],
    ],
    'compliance' => [
        [
            'icon' => 'award-line',
            'title' => 'ISO 9001:2015',
            'subtitle' => 'Quality Management',
            'desc' => 'Sertifikasi kualitas internasional memastikan setiap project dieksekusi dengan standar excellence tertinggi.',
            'points' => ['Proses Terstruktur', 'Quality Control', 'Continuous Improvement'],
        ],
        [
            'icon' => 'shield-check-line',
            'title' => 'TKDN & Compliance',
            'subtitle' => 'Indonesia Regulation',
            'desc' => 'Fully compliant dengan regulasi Indonesia termasuk TKDN dan cybersecurity standards.',
            'points' => ['Lokal Content', 'Data Sovereignty', 'Audit Ready'],
        ],
    ],
    'trusted' => [
        ['name' => 'Kementerian Agama', 'subtitle' => 'Government', 'logo' => '/clients/kementerian-agama-new-logo.png'],
        ['name' => 'Polri', 'subtitle' => 'Law Enforcement', 'logo' => '/clients/lambang-polri.png'],
        ['name' => 'TMII', 'subtitle' => 'Heritage', 'logo' => '/clients/2560px-tmii-logo-svg.png'],
        ['name' => 'Komdigi', 'subtitle' => 'Government', 'logo' => '/clients/logo-kementerian-komunikasi-dan-digital-republik-indonesia-komdigi.svg'],
        ['name' => 'Bawaslu', 'subtitle' => 'Election', 'logo' => '/clients/logo-bawaslu.png'],
        ['name' => 'LKPP', 'subtitle' => 'Procurement', 'logo' => '/clients/logo-lkpp.png'],
        ['name' => 'Kemenpan', 'subtitle' => 'Government', 'logo' => '/clients/logo-of-the-ministry-of-manpower-of-the-republic-of-indonesia-svg.png'],
        ['name' => 'Unhan', 'subtitle' => 'Military', 'logo' => '/clients/logo-unhan.png'],
        ['name' => 'PUPR', 'subtitle' => 'Infrastructure', 'logo' => '/clients/pupr.png'],
        ['name' => 'BSN', 'subtitle' => 'Standards', 'logo' => '/clients/badan-standardisasi-nasional-seeklogo.png'],
        ['name' => 'RSPON', 'subtitle' => 'Healthcare', 'logo' => '/clients/rspon.png'],
        ['name' => 'Ristek-Dikti', 'subtitle' => 'Research', 'logo' => '/clients/ristekdikti-logo-f092eadfb2-seeklogo-com.png'],
    ],
    'portfolio' => [
        'items' => [
            'av' => [
                'title' => 'Government AV & Broadcasting',
                'client' => 'Kementerian Agama',
                'loc' => 'Jakarta',
                'shortDesc' => 'Audio-visual infrastructure untuk broadcast & streaming nasional',
                'desc' => 'Infrastruktur AV modern dengan 4K broadcasting, live streaming, dan disaster recovery untuk ministry-wide events.',
                'img' => 'https://images.unsplash.com/photo-1451187580459-fdce2b798603?w=600&h=400&fit=crop',
                'cat' => 'infra',
                'featured' => true,
                'status' => 'completed',
            ],
            'office' => [
                'title' => 'Smart Office Automation',
                'client' => 'Enterprise Multinasional',
                'loc' => 'Jakarta',
                'shortDesc' => 'Otomasi ruang kerja dengan IoT & AI',
                'desc' => 'Implementasi smart office dengan gesture recognition, lighting automation, dan energy optimization.',
                'img' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
                'cat' => 'smart',
                'featured' => true,
                'status' => 'completed',
            ],
            'micro' => [
                'title' => 'Microteaching Platform',
                'client' => 'Universitas Indonesia',
                'loc' => 'Jakarta',
                'shortDesc' => 'Platform pelatihan guru dengan AI monitoring',
                'desc' => 'Sistem pelatihan guru dengan real-time video analysis, feedback automation, dan performance tracking.',
                'img' => 'https://images.unsplash.com/photo-1524178232363-1468b7ef7000?w=600&h=400&fit=crop',
                'cat' => 'edu',
                'featured' => false,
                'status' => 'completed',
            ],
            'infra' => [
                'title' => 'Datacenter Consolidation',
                'client' => 'Government IT Agency',
                'loc' => 'Jakarta & Bandung',
                'shortDesc' => 'Konsolidasi datacenter multi-lokasi',
                'desc' => 'Geo-redundant datacenter setup dengan automated failover dan real-time monitoring untuk 24/7 availability.',
                'img' => 'https://images.unsplash.com/photo-1558494949-ef010cb60b97?w=600&h=400&fit=crop',
                'cat' => 'infra',
                'featured' => true,
                'status' => 'completed',
            ],
            'net' => [
                'title' => 'Enterprise Network Security',
                'client' => 'Bank Terkemuka',
                'loc' => 'Jakarta',
                'shortDesc' => 'Jaringan secure dengan zero-trust architecture',
                'desc' => 'Implementasi SD-WAN, firewall advanced, dan intrusion detection untuk keamanan enterprise banking-grade.',
                'img' => 'https://images.unsplash.com/photo-1516321318423-f06f70504504?w=600&h=400&fit=crop',
                'cat' => 'infra',
                'featured' => false,
                'status' => 'completed',
            ],
            'rental' => [
                'title' => 'Smart Rental Management',
                'client' => 'Equipment Rental Co',
                'loc' => 'Jakarta',
                'shortDesc' => 'Platform rental dengan IoT tracking',
                'desc' => 'Sistem manajemen rental dengan GPS tracking, predictive maintenance, dan mobile app untuk customers.',
                'img' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
                'cat' => 'smart',
                'featured' => false,
                'status' => 'completed',
            ],
        ],
        'filterOrder' => ['all', 'edu', 'infra', 'smart'],
    ],
    'finalCta' => [
        'label' => 'SIAP MULAI?',
        'headline' => 'Transformasi Digital Dimulai dari Sini',
        'description' => 'Konsultasikan kebutuhan transformasi digital Anda dengan expert kami. Gratis dan tanpa komitmen.',
        'primaryText' => 'Jadwalkan Konsultasi',
        'primaryLink' => '#contact',
        'secondaryText' => 'Lihat Case Study',
        'secondaryLink' => '#portfolio',
    ],
    'contact' => [
        'title' => 'Hubungi Kami',
        'phone' => '+62-21-7274-0123',
        'address' => 'Jl. Gatot Subroto Kav. 8, Jakarta Selatan 12950',
        'formLabels' => [
            'name' => 'Nama Lengkap',
            'institution' => 'Institusi / Perusahaan',
            'email' => 'Email',
            'phone' => 'Nomor Telepon',
            'category' => 'Kategori Layanan',
            'message' => 'Pesan Anda',
        ],
        'submitText' => 'Kirim Pesan',
        'successMsg' => 'Terima kasih! Kami akan menghubungi Anda dalam 24 jam.',
    ],
    'seo' => [
        'title' => 'PT Dua Kawan Sejahtera Indonesia | Solusi ICT Terintegrasi',
        'description' => 'Solusi ICT terintegrasi untuk transformasi digital bisnis Indonesia. Infrastruktur IT, Smart Education, AI & IoT.',
        'keywords' => 'ICT, transformasi digital, infrastruktur IT, smart education, AI, IoT, enterprise solutions',
        'ogImage' => '/logo/main.png',
    ],
    'social' => [
        'linkedin' => 'https://linkedin.com/company/dksi',
        'instagram' => 'https://instagram.com/dksi.official',
        'twitter' => 'https://twitter.com/dksi_official',
        'facebook' => 'https://facebook.com/dksi.official',
        'youtube' => 'https://youtube.com/@dksi',
        'email' => 'mailto:info@dksi.co.id',
    ],
    'meta' => [
        'publishedCount' => 22,
        'draftsCount' => 0,
        'version' => '2.0',
        'lastPublished' => now()->toIso8601String(),
    ],
];
